git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

customCommands:
  - key: 'P'
    description: 'Checkout PR by number'
    command: 'gh pr checkout {{.Form.PRNumber}}'
    context: 'global'
    prompts:
      - type: 'input'
        title: 'PR number'
        key: 'PRNumber'
    loadingText: 'Checking out PR...'
